version: "3.9"

services:
  taskflow-api:
    build:
      context: .
      dockerfile: TaskFlow.API/Dockerfile
    container_name: taskflow-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=TaskFlowAPIDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379"
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: taskflow-redis
    ports:
      - "6379:6379"

volumes:
  sql-data:
